spring:
  application:
    name: final-assignment-backend

server:
  port: 8080

app:
  hadoop:
    mode: local
    local-base-path: ${user.home}/Desktop/hadoop/local-dev
    config-dir: ${HADOOP_CONF_DIR:${HADOOP_HOME:${user.home}/hadoop}/etc/hadoop}
    input-path: /datasets/input
    output-path: /datasets/output
